Feature 123 pollutant recommendation view
Metatavu/megasense-data-portal-ui pull request #124
Opened 2021-08-13 10:28 UTC by Chi-Chu319

resolves 123

2021-08-13 12:30 UTC, Daniilmass requested changes

2021-08-13 12:30 UTC, Daniilmass commented on src/components/views/management-medical-condition-view/management-medical-condition-view.tsx
> +            }
This should be moved to a separate private method. Since it is not a good idea to have maps within the HTML code

2021-08-13 12:30 UTC, Daniilmass commented on src/components/views/management-medical-condition-view/management-medical-condition-view.tsx
> +            conditions.map(condition => this.renderCondition(condition))
```suggestion
          searchInput ? 
          conditions.map(condition => condition.conditionName.toLowerCase().includes(searchInput.toLowerCase()) && this.renderCondition(condition)) : 
          conditions.map(condition => this.renderCondition(condition))
```

2021-08-13 12:30 UTC, Daniilmass commented on src/components/views/management-medical-condition-view/management-medical-condition-view.tsx
> +    ];
Could those be applied as styles from the stylesheet? I.e the screen width based on the screen size could be done in a stylesheet. Or should it be kept here?

2021-08-13 12:42 UTC, Chi-Chu319 commented on src/components/views/management-medical-condition-view/management-medical-condition-view.tsx
> +    ];
Well with the create style you can only modify the style at css level. Say if you want to modify the width you basically have to modify it for row and title, it require some specific configurations and It might not work. The datagrid take the row width from the actually component, and it is not meant to be dynamic. So my answer is its much easier to keep it here as this is how the datagrid should work.

2021-08-16 08:00 UTC, Daniilmass commented on src/types/index.ts
> +
It is misaligned to other types. Please fix the indentation

2021-08-16 08:04 UTC, Daniilmass commented on package-lock.json
> +        "@types/classnames": "^2.3.1",
The package-lock.json should not be pushed to the PR. Please remove it

2021-08-16 08:43 UTC, Daniilmass approved these changes

2021-08-16 08:43 UTC, merged