Feature 146 creating deleting editing routing mode
Metatavu/megasense-data-portal-ui pull request #150
Opened 2021-11-01 12:22 UTC by Chi-Chu319

resolves #146

2021-11-03 09:52 UTC, Daniilmass requested changes

2021-11-03 09:52 UTC, Daniilmass commented on src/components/generic/manageable-items/medical-condition-accordion.tsx
> +  private onDataGridRowRemove = () => {
Fix indentation

2021-11-03 09:52 UTC, Daniilmass commented on src/components/generic/manageable-items/medical-condition-accordion.tsx
> +    }
```suggestion
    if (!editingName) {
    
      this.setState({
        editingName: true
      });
      
      return;
    }
```

2021-11-03 09:52 UTC, Daniilmass commented on src/components/generic/manageable-items/routing-mode-accordion.tsx
> +class DefaultRoutingModeAccordion extends React.Component<Props, State> {
It is not a "header"

2021-11-03 09:52 UTC, Daniilmass commented on src/components/generic/manageable-items/routing-mode-accordion.tsx
> +    super(props);
Add TSdocs

2021-11-03 09:52 UTC, Daniilmass commented on src/components/generic/manageable-items/routing-mode-accordion.tsx
> +  /**
```suggestion
  }
  
  /**
```

2021-11-03 09:52 UTC, Daniilmass commented on src/components/generic/manageable-items/routing-mode-accordion.tsx
> +  private onDataGridRowRemove = () => {
Fix indentation

2021-11-03 09:52 UTC, Daniilmass commented on src/components/generic/routing-mode-icon/routing-mode-icon-renderer.tsx
> +    super(props);
Add TSdocs

2021-11-03 09:52 UTC, Daniilmass commented on src/components/generic/routing-mode-icon/routing-mode-icon-renderer.tsx
> +    const { iconName, htmlColor } = this.props;
Add TSdocs

2021-11-03 09:52 UTC, Daniilmass commented on src/components/generic/routing-mode-icon/routing-mode-icon-renderer.tsx
> +}
```suggestion
    }
  }
}
```

2021-11-03 09:52 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +  private routeOffsets = (routeAlts: RoutingModeData[]): RoutingModeData[] => {
Methdod name and description are too similar to the method above... Should have more difference

2021-11-03 09:52 UTC, Daniilmass commented on src/components/views/management-routing-mode/management-routing-mode.tsx
> +    callback();
No need for a callback here

2021-11-03 09:52 UTC, Daniilmass commented on src/components/views/management-routing-mode/management-routing-mode.tsx
> +    const { defaultRoutingModes } = this.state;
No need for a callback here

2021-11-03 09:52 UTC, Daniilmass commented on src/components/generic/manageable-items/routing-mode-accordion.tsx
> +  onRoutingModeChangeRaw: (callback: () => void) => (defaultRoutingMode: DefaultRoutingMode) => void;
No need for a callback here

2021-11-03 09:52 UTC, Daniilmass commented on src/components/generic/manageable-items/routing-mode-accordion.tsx
> +    onRoutingModeChangeRaw(callback)(updatedRoutingMode);
No need for a callback here

2021-11-05 09:19 UTC, Daniilmass requested changes

2021-11-05 09:19 UTC, Daniilmass commented on src/components/views/management-medical-condition-view/management-medical-condition-view.tsx
> +          medicalConditions.map(this.renderCondition)
```suggestion
          medicalConditions.map(this.renderCondition);
```

2021-11-05 09:19 UTC, Daniilmass commented on src/components/views/management-medical-condition-view/management-medical-condition-view.tsx
> +          })
```suggestion
          });
```

2021-11-05 09:19 UTC, Daniilmass commented on src/components/views/management-routing-mode/management-routing-mode.tsx
>            })
```suggestion
          });
```

2021-11-05 09:19 UTC, Daniilmass commented on src/components/views/management-routing-mode/management-routing-mode.tsx
> +          })
```suggestion
          });
```

2021-11-05 09:19 UTC, Daniilmass commented on src/components/views/management-routing-mode/management-routing-mode.tsx
> +    private onCreateNewRoutingModeClick = () => {
```suggestion
    /**
     * Create new routing mode click handler
     */
    private onCreateNewRoutingModeClick = () => {
```

2021-11-05 10:01 UTC, Chi-Chu319 commented on src/components/views/management-medical-condition-view/management-medical-condition-view.tsx
> +          medicalConditions.map(this.renderCondition)
You cant put semicolon there because its not the end of this expression, same as other few

2021-11-05 12:24 UTC, Kaemppi commented on src/localization/fi.json
>        "refresh": "Päivittää",
```suggestion
      "refresh": "Päivitä",
```

2021-11-05 12:28 UTC, Kaemppi commented on src/localization/fi.json
>        "title": "Terveydentila",
```suggestion
      "title": "Sairaus",
```

2021-11-05 12:28 UTC, Kaemppi commented on src/localization/fi.json
> +      "newCondition": "Uusi terveydentila",
```suggestion
      "newCondition": "Uusi sairaus",
```

2021-11-05 12:28 UTC, Kaemppi commented on src/localization/fi.json
> +      "medicalConditionName": "Terveydentilan nimi",
```suggestion
      "medicalConditionName": "Sairauden nimi",
```

2021-11-05 12:29 UTC, Kaemppi commented on src/localization/fi.json
>            "text": "Anna uuden terveydentilan nimi.",
```suggestion
          "title": "Luo uusi sairaus",
          "text": "Anna uuden sairauden nimi.",
```

2021-11-05 12:30 UTC, Kaemppi commented on src/localization/fi.json
>            "title": "Poistetaan terveydentila",
```suggestion
          "newConditionName": "Sairauden nimi"
        },
        "deleteCondition": {
          "title": "Poista sairaus",
```

2021-11-05 12:30 UTC, Kaemppi commented on src/localization/fi.json
> +          "text": "Haluatko varmasti poistaa tämän terveydentilan?"
```suggestion
          "text": "Haluatko varmasti poistaa tämän sairauden?"
```

2021-11-05 12:31 UTC, Kaemppi commented on src/localization/fi.json
> +      "newRoutingMode": "Uusi reittityyppi",
```suggestion
      "newRoutingMode": "Uusi reititystyyppi",
```

2021-11-05 12:33 UTC, Kaemppi commented on src/localization/fi.json
> +      "newRoutingMode": "Uusi reittityyppi",
```suggestion
      "title": "Reititystapa",
      "icon": "Ikoni",
      "newRoutingMode": "Uusi reititystapa",
```

2021-11-05 12:35 UTC, Kaemppi commented on src/localization/fi.json
> +          "text": "Haluatko varmasti poistaa tämän reittityypin?"
```suggestion
          "title": "Luo uusi reititystapa",
          "text": "Anna uuden reititystavan nimi.",
          "newRoutingModeName": "Reititystavan nimi"
        },
        "deleteRoutingMode": {
          "title": "Poista reititystapa",
          "text": "Haluatko varmasti poistaa tämän reititystavan?"
```

2021-11-05 12:35 UTC, Kaemppi commented on src/localization/fi.json
> +    "remove": "Poistaa",
```suggestion
    "remove": "Poista",
```

2021-11-05 12:36 UTC, Kaemppi commented on src/localization/fi.json
> +    "confirm": "Vahvistaa"
```suggestion
    "confirm": "Vahvista"
```

2021-11-05 12:37 UTC, Kaemppi requested changes
Check these finnish translations

2021-11-05 12:42 UTC, Daniilmass commented on src/localization/fi.json
> +      "newRoutingMode": "Uusi reititystapa",
```suggestion
      "title": "Reititystapa",
      "icon": "Ikoni",
      "newRoutingMode": "Uusi reititystapa",
```

2021-11-08 09:18 UTC, Daniilmass requested changes

2021-11-08 09:18 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +          })
```suggestion

          this.setState({ 
            airQuality: airQuality,
            mapBounds: mapBounds,
            pollutantPointScores: pollutantPointScores,
            pollutantsStatistics: pollutantsStatistics
          });
```

2021-11-08 09:18 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +      })
```suggestion
      this.setState({
        error
      });
```

2021-11-08 09:18 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +
```suggestion
    }
```

2021-11-08 09:18 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +          })
```suggestion
          this.setState({
            pollutants
          });
```

2021-11-08 09:18 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +   * Loads default routing modes
```suggestion
  /**
   * Loads default routing modes
```

2021-11-08 09:18 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +        })
```suggestion
        this.setState({
          defaultRoutingModes
        });
```

2021-11-08 09:18 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +      })
```suggestion
      this.setState({
        error
      });
```

2021-11-08 09:18 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +
```suggestion
    }
```

2021-11-08 09:18 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +            { ((routeAlts.length) &&
```suggestion
            { (routeAlts.length &&
```

2021-11-08 09:18 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +    return process.env.REACT_APP_OTP_LOW_RESOURCES === "TRUE";
Add TSdocs

2021-11-09 07:44 UTC, merged