Feature 169 settings polishing
Metatavu/megasense-data-portal-ui pull request #170
Opened 2022-01-14 11:38 UTC by Chi-Chu319

resolves #169

2022-01-19 12:14 UTC, Daniilmass requested changes

2022-01-19 12:14 UTC, Daniilmass commented on src/components/settings/settings.tsx
> +  private onHomeAddressChange = (event: React.ChangeEvent<HTMLInputElement>) => {
Add TSdocs "event" parameter

2022-01-19 12:14 UTC, Daniilmass commented on src/components/settings/settings.tsx
> +  private onMedicalConditionCheck = (medicalConditionId: string) => (event: React.ChangeEvent<HTMLInputElement>) => {
Add TSdocs "medicalConditionId" parameter

2022-01-20 07:39 UTC, Chi-Chu319 commented on src/components/settings/settings.tsx
> +  private onHomeAddressChange = (event: React.ChangeEvent<HTMLInputElement>) => {
```suggestion
  /**
   * On home address change handler
   *
   * @param event event
   */
  private onHomeAddressChange = (event: React.ChangeEvent<HTMLInputElement>) => {
```

2022-01-20 07:40 UTC, Chi-Chu319 commented on src/components/settings/settings.tsx
> +  private onMedicalConditionCheck = (medicalConditionId: string) => (event: React.ChangeEvent<HTMLInputElement>) => {
```suggestion
  /**
   * On medical condition check handler
   *
   * @param medicalConditionId medical condition id
   * @param event event
   */
  private onMedicalConditionCheck = (medicalConditionId: string) => (event: React.ChangeEvent<HTMLInputElement>) => {
```

2022-01-20 07:43 UTC, Daniilmass approved these changes

2022-01-20 07:43 UTC, merged