Feature home screen improvements
Metatavu/megasense-data-portal-ui pull request #63
Opened 2021-01-13 07:52 UTC by Valmetti

Closes #60

2021-01-13 08:02 UTC, Daniilmass commented on src/components/layouts/app-layout/app-layout.tsx
> +    const { accessToken, keycloak, routing } = this.props;
Add TS docs here

2021-01-13 08:03 UTC, Daniilmass commented on src/components/screens/home-screen/home-screen.tsx
> +import { Typography, WithStyles, withStyles, Button, Grid, } from "@material-ui/core";
```suggestion
import { Typography, WithStyles, withStyles, Button, Grid } from "@material-ui/core";
```

2021-01-13 08:07 UTC, Daniilmass commented on src/components/screens/home-screen/home-screen.tsx
>      );
Move this whole block to a separate private method below. Could be called "renderHomeScreen"

2021-01-13 08:08 UTC, Daniilmass commented on src/components/screens/home-screen/home-screen.tsx
> +              }}
Move the onClick handler to a separate private method below

2021-01-13 08:10 UTC, Kaemppi commented on src/components/screens/home-screen/home-screen.tsx
> +        </AppLayout>
```suggestion
        <AppLayout accessToken={ accessToken } keycloak={ keycloak }>
          <Grid container className={ classes.backgroundContainer }>
            <Typography className={ classes.title } variant="h3">
              { strings.hello } { userDisplayName }
            </Typography>
          </Grid>
        </AppLayout>
```

2021-01-13 08:10 UTC, Daniilmass commented on src/components/screens/home-screen/home-screen.tsx
> +  private navigateTo = (path : string) => () => {
```suggestion
   * @param path path string
   */
  private navigateTo = (path: string) => () => {
```

2021-01-13 08:13 UTC, Daniilmass requested changes
Component's render return should avoid having long, conditional or complicated returns. Please split it in private methods and call them in the component render return.

2021-01-13 08:13 UTC, Kaemppi reviewed
just a minor comment

2021-01-13 08:54 UTC, Valmetti commented on src/components/screens/home-screen/home-screen.tsx
> +  private navigateTo = (path : string) => () => {
the => on line 123 actually has to be as it was. I don't know exactly why, because Lauri helped with this bit, but if i change it to the suggested way, it fails to compile.
![image](https://user-images.githubusercontent.com/76946183/104428535-461d3100-558d-11eb-9b59-1310ebe454ec.png)

2021-01-13 10:07 UTC, Daniilmass commented on src/components/screens/home-screen/home-screen.tsx
> +  private navigateTo = (path : string) => () => {
Sorry, I did not recognise the issue correctly. I have updated my comment now :) There is an extra "()" which should be removed

2021-01-13 16:54 UTC, anttileppa requested changes

2021-01-13 16:54 UTC, anttileppa commented on src/components/layouts/app-layout/app-layout.tsx
> +      <div className={ classes.root}>
```suggestion
      <div className={ classes.root }>
```

2021-01-13 16:54 UTC, anttileppa commented on src/components/layouts/app-layout/app-layout.tsx
> +        { !hideHeader &&
Move hideHeader check to renderHeader method

2021-01-13 16:54 UTC, anttileppa commented on src/components/screens/home-screen/home-screen.tsx
>    public render() {
render and renderHomeScreen methods do exactly same thing, so there is no need for separate renderHomeScreen -method

2021-01-13 16:54 UTC, anttileppa commented on src/components/screens/home-screen/home-screen.tsx
> +  private logIn = () => {
This is an event handle for button click so it should be named onLoginButtonClick and moved to the bottom of the class

2021-01-13 16:54 UTC, anttileppa commented on src/components/screens/home-screen/home-screen.tsx
> +              onClick={ () => this.navigateTo("/map") }
Move this to private method

2021-01-13 16:54 UTC, anttileppa commented on src/components/screens/home-screen/home-screen.tsx
> +  private navigateTo = (path: string) => {
Navigation should be done with AppLayout navigation property

2021-01-13 16:54 UTC, anttileppa commented on src/localization/en.json
>      "login": "Log in",
it's spelled Login

2021-01-14 09:22 UTC, Daniilmass commented on src/components/layouts/app-layout/app-layout.tsx
> +}
```suggestion
  }
```

2021-01-14 09:23 UTC, Daniilmass requested changes
Spaces missing

2021-01-14 09:24 UTC, Daniilmass commented on src/components/layouts/app-layout/app-layout.tsx
> +      <div className={ classes.root}>
```suggestion
      <div className={ classes.root }>
```

2021-01-14 10:10 UTC, Daniilmass approved these changes

2021-01-14 12:59 UTC, merged