Feature 80 offer saved locations at first
Metatavu/megasense-data-portal-ui pull request #84
Opened 2021-02-16 13:02 UTC by baherami

Adds saved locations on top of options in app.

2021-02-16 13:04 UTC, baherami commented on src/components/screens/map-screen/map-screen.tsx
> +    this.getUserFavouriteLocations().then(() => this.setlocationOptions());
fixed typo in the other commit.

2021-02-16 13:05 UTC, baherami commented on src/components/screens/map-screen/map-screen.tsx
> +    this.getUserFavouriteLocations().then(() => this.setLocationOptions());
fixed typo

2021-02-16 13:27 UTC, Daniilmass reviewed
Hi, could you please make sure to keep the old styling in terms of { abc } and not {abc}. I will continue the review after it is done.

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +          showDrawer={true}
```suggestion
          showDrawer={ true }
```

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +              <CircularProgress size={64} />
```suggestion
            <div className={ classes.loader }>
              <CircularProgress size={ 64 } />
```

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +            <CircularProgress size={64} />
```suggestion
          <div className={ classes.loader }>
            <CircularProgress size={ 64 } />
```

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +        clearError={this.onClearError}
```suggestion
      <AppLayout
        accessToken={ accessToken }
        keycloak={ keycloak }
        showDrawer={ true }
        drawerContent={ this.renderDrawerContent() }
        error={ error }
        clearError={ this.onClearError }
```

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +        {this.renderSaveLocationConfirmDialog()}
```suggestion
        { this.renderMap() }
        { this.renderSaveRouteConfirmDialog() }
        { this.renderSaveLocationConfirmDialog() }
```

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +        <Toolbar className={classes.toolbar}>
```suggestion
        <Toolbar className={ classes.toolbar }>
```

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +          onUserRouteSelect={this.onUserRouteSelect}
```suggestion
        { this.renderRoutingForm() }
        <SavedRoutes
          savedRoutes={ userSavedRoutes }
          showSavedRoutes={ !!accessToken }
          onDeleteUserSavedRoute={ this.onDeleteUserSavedRoute }
          onUserRouteSelect={ this.onUserRouteSelect }
```

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +          onUserLocationSelect={this.onUserLocationSelect}
```suggestion
          savedFavouriteLocations={ userFavouriteLocations }
          showFavouriteLocations={ !!accessToken }
          onDeleteUserFavouriteLocation={ this.onDeleteUserFavouriteLocation }
          onUserLocationSelect={ this.onUserLocationSelect }
```

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +    const locationFromCoordinates = `${firstItem[0]},${firstItem[1]}`;
```suggestion
    const locationFromCoordinates = `${ firstItem[0] },${ firstItem[1] }`;
```

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +    const locationToCoordinates = `${lastItem[0]},${lastItem[1]}`;
```suggestion
    const locationToCoordinates = `${ lastItem[0] },${ lastItem[1] }`;
```

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +    );
```suggestion
    );
    
```

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +  /**
```suggestion
  };
  
  /**
```

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +  };
```suggestion
  };
  
```

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +  };
You do not need to end a private method with ```;```. Please remove all the ```;``` that you used in the end of private methods in this PR

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +              >
Please make sure to keep the old styling in terms of ```{ abc }``` and not ```{abc}```

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +        <div className={classes.inputFieldContainer}>
Please make sure to keep the old styling in terms of { abc } and not {abc}

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +                  {...params}
Please make sure to keep the old styling in terms of { abc } and not {abc}

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +            value={locationTo}
Please make sure to keep the old styling in terms of { abc } and not {abc}

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +                className={classes.autoCompleteInputWrapper}
Please make sure to keep the old styling in terms of { abc } and not {abc}

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +                  {...params}
Please make sure to keep the old styling in terms of { abc } and not {abc}

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +          <Box mt={4}>
Please make sure to keep the old styling in terms of { abc } and not {abc}

2021-02-16 13:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +            <MuiPickersUtilsProvider utils={MomentUtils}>
Please make sure to keep the old styling in terms of { abc } and not {abc}

2021-02-16 13:41 UTC, baherami commented on src/components/screens/map-screen/map-screen.tsx
> +          showDrawer={true}
reverted

2021-02-16 13:44 UTC, baherami commented
reverted general changes to the file.

2021-02-16 16:28 UTC, Daniilmass requested changes

2021-02-16 16:28 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +   private setLocationOptions = () => {
```suggestion
   */
   private setLocationOptions = () => {
```
No space needed between Tsdocs and method

2021-02-16 16:28 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +  }
```suggestion
    this.setState({ locationFromOptions, locationToOptions });
  }
  
```

2021-02-17 07:19 UTC, baherami commented on src/components/screens/map-screen/map-screen.tsx
> +  }
PEP8 confusion. Fixed

2021-02-17 07:22 UTC, baherami commented on src/components/screens/map-screen/map-screen.tsx
> +   private setLocationOptions = () => {
done

2021-02-18 12:23 UTC, Daniilmass requested changes
In Typescript usually you do not have do describe a return type in the beginning of the method. It is automatically taken from whatever is returned

2021-02-18 12:23 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +   */
Include parameters to the Tsdocs (see other private methods with parameters as a reference)

2021-02-18 12:23 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +      return { name, coordinates };
```suggestion
  private mapLocationsFromFavouriteLocations = (favouriteLocations: FavouriteLocation[]) => {
    return favouriteLocations.map((element) => {
      const name = element.name;
      const coordinates = element.latitude + "," + element.longitude;
      return { name, coordinates } as Location;
```
In this case it is better to use ```as Location``` if you want your return to have a specific type, also a space is missing

2021-02-18 12:23 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +   * @param keyword the string to search
```suggestion
   * Filters favourite locations with a specific keyword
   *
   * @param keyword the string to search
```
Empty line needed between description and other things

2021-02-18 12:23 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +    const {userFavouriteLocations} = this.state
Please remove return type here as well. It is not needed since you modify the array which already has a ```FavouriteLocation []``` type. So it will remain. Also a space is missing after ```keyword:```. Also ```const {userFavouriteLocations} = this.state``` should end with ```;```

2021-02-18 12:23 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +        )
```suggestion
        );
```

2021-02-18 12:23 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +   * @param keyword the string to search
```suggestion
  /**
   * Get locations from favourite locations.
   *
   * @param keyword the string to search
```

2021-02-18 12:23 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +  this.mapLocationsFromFavouriteLocations(this.searchInFavouriteLocations(keyword));
```suggestion
  private getLocationsFromFavouriteLocations = (keyword:string) => { 
    this.mapLocationsFromFavouriteLocations(this.searchInFavouriteLocations(keyword));
  }
```

2021-02-18 12:23 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +  this.mapLocationsFromFavouriteLocations(this.searchInFavouriteLocations(keyword));
Do you actually need this private method? see below

2021-02-18 12:23 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +      locationFromOptions.unshift(...this.getLocationsFromFavouriteLocations(locationFromTextInput));
Do you actually need to use a separate private method here? Can you just use ```this.mapLocationsFromFavouriteLocations(this.searchInFavouriteLocations(locationFromTextInput));```?

2021-02-18 12:23 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +      locationToOptions.unshift(...this.getLocationsFromFavouriteLocations(locationToTextInput));
Do you actually need to use a separate private method here? Can you just use this.mapLocationsFromFavouriteLocations(this.searchInFavouriteLocations(locationToTextInput));?

2021-02-18 12:23 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +private nominateCall = async (keyword: string): Promise<Location[]> => {
Check indentation
and add an empty line between description and params

2021-02-18 12:23 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +  try{
```suggestion
  try {
```

2021-02-18 12:23 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +}
Check indentation

2021-02-18 12:23 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +return error;
```suggestion
  return error;
```

2021-02-18 12:43 UTC, baherami commented on src/components/screens/map-screen/map-screen.tsx
> +return error;
all done. sorry i forgot to format my code before commit.

2021-02-18 12:49 UTC, Daniilmass requested changes

2021-02-18 12:49 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +   * @param keyword the keyword to call the api
```suggestion
   * Calls the api for similar locations and translates it to option format
   *
   * @param keyword the keyword to call the api
```

2021-02-18 12:49 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +   *
```suggestion
   * 
```

2021-02-18 13:04 UTC, Daniilmass approved these changes

2021-02-18 13:04 UTC, merged