Feature-88 add map data overlay
Metatavu/megasense-data-portal-ui pull request #91
Opened 2021-03-09 18:39 UTC by baherami

2021-03-10 10:04 UTC, Daniilmass requested changes
Could you please do the fixes and reformat the pollutant-control.tsx according to some other similar classes. favourite-locations.tsx could be a good reference example

2021-03-10 10:04 UTC, Daniilmass commented on src/components/polutant-control/polutant-control.tsx
> +    const { classes } = this.props;
This is an example of how you initiate a render method:
```
  /**
   * Map screen render method
   */
  public render = () => {
```

2021-03-10 11:09 UTC, baherami commented on src/components/polutant-control/polutant-control.styles.ts
> +  },
fixed

2021-03-10 11:11 UTC, baherami commented on src/components/polutant-control/polutant-control.styles.ts
> +import { createStyles } from "@material-ui/core";
fixed

2021-03-10 12:12 UTC, Daniilmass commented on src/components/pollutant-control/pollutant-control.tsx
> +          <IconButton className={classes.button}
Please use ```style={  }``` instead of a className. See other classes for an example. Please check all occurrences below

2021-03-10 12:13 UTC, Daniilmass commented on src/components/pollutant-control/pollutant-control.tsx
> +            onClick={this.zoomIn}
```suggestion
            title={ strings.map.zoomIn }
            onClick={ this.zoomIn }
```
Spaces are missing. Please check all occurrences below

2021-03-10 12:13 UTC, Daniilmass commented on src/components/pollutant-control/pollutant-control.tsx
> +            onClick={this.zoomOut}
Spaces are missing. Please check all occurrences below

2021-03-10 12:15 UTC, Daniilmass commented on src/components/pollutant-control/pollutant-control.tsx
> +          >          {showPollutantData ? strings.map.showMap : strings.map.showDataOverlay} </Typography>
```suggestion
          <Typography
            variant="h2"
            color="primary"
            className={classes.toggleMap}
            onClick={this.toggleMap}
          >
            { showPollutantData ? strings.map.showMap : strings.map.showDataOverlay }
          </Typography>
```
Should be something like this

2021-03-10 12:16 UTC, Daniilmass commented on src/components/pollutant-control/pollutant-control.tsx
> +              zoomControl={false}
Please add spaces before and after { and }. Also check other occurrences in this class

2021-03-10 12:18 UTC, Daniilmass commented on src/components/pollutant-control/pollutant-control.tsx
> +
You could call the Props variable here with
```
const { parentMapRef } = this.props;
```

2021-03-10 12:19 UTC, Daniilmass commented on src/components/pollutant-control/pollutant-control.tsx
> +    this.props.parentMapRef.current?.leafletElement.zoomIn(1)
You could call the Props variable here with
```
const { parentMapRef } = this.props;
```

2021-03-10 12:19 UTC, Daniilmass commented on src/components/pollutant-control/pollutant-control.tsx
> +    this.props.parentMapRef.current?.leafletElement.zoomOut(1)
You could call the Props variable here with
```
const { parentMapRef } = this.props;
```

2021-03-10 12:20 UTC, Daniilmass commented on src/components/pollutant-control/pollutant-control.tsx
> +    this.props.parentMapRef.current?.leafletElement.zoomIn(1)
The ```;``` is missing in the end of line

2021-03-10 12:21 UTC, Daniilmass commented on src/components/pollutant-control/pollutant-control.tsx
> +    this.props.parentMapRef.current?.leafletElement.zoomOut(1)
The ; is missing in the end of line

2021-03-10 12:21 UTC, Daniilmass commented on src/components/pollutant-control/pollutant-control.tsx
> +    this.toggleLayer(!showPollutantData)
The ; are missing in the end of line

2021-03-10 12:21 UTC, Daniilmass commented on src/components/pollutant-control/pollutant-control.tsx
> +
No space needed here

2021-03-10 12:22 UTC, Daniilmass commented on src/components/pollutant-control/pollutant-control.tsx
> +    const map = this.props.parentMapRef.current?.leafletElement;
It would look cleaner if you could call the Props variable here with
```
const { parentMapRef, parentLayerRef } = this.props;
```

2021-03-10 12:23 UTC, Daniilmass commented on src/components/pollutant-control/pollutant-control.tsx
> +
```suggestion
```
Remove empty line

2021-03-10 12:25 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +
```suggestion
```
Remove empty line

2021-03-10 12:26 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +
```suggestion
```
Remove empty line

2021-03-10 12:26 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +
```suggestion
```
Remove empty line

2021-03-10 12:27 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +>
```suggestion
        <PollutantControl
          parentMapRef={ this.mapRef }
          parentLayerRef={ this.overlayRef }
          airQuality={ this.state.airQuality }
        >
```

2021-03-10 12:28 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +
```suggestion
        </PollutantControl>
```
Remove empty lines

2021-03-10 12:28 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +          <HeatmapLayer ref={this.overlayRef}
```suggestion
          <HeatmapLayer
            ref={ this.overlayRef } 
```

2021-03-10 12:29 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +
```suggestion
```
Remove empty lines

2021-03-10 12:30 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +    if (this.mapRef.current != null) {
```suggestion

    if (this.mapRef.current != null) {
```
Empty lines before if statements is usually a good idea

2021-03-10 12:30 UTC, Daniilmass commented on src/components/screens/map-screen/map-screen.tsx
> +import PollutantControl from "../../pollutant-control/pollutant-control"
```suggestion
import PollutantControl from "../../pollutant-control/pollutant-control";
```

2021-03-10 12:31 UTC, Daniilmass commented on src/localization/strings.ts
> +  };
```suggestion
  };
  
```

2021-03-11 07:11 UTC, Daniilmass approved these changes

2021-03-11 07:11 UTC, merged